server {
    server_name fredima.de www.fredima.de;
    root /var/www/fredima.de/public/;
    index index.php index.html;
    
    error_page 400 /error/400.html;
    error_page 403 /error/403.html;
    error_page 404 /error/404.html;
    error_page 500 /error/500.html;
    error_page 503 /error/503.html;
    
    location /private {
        auth_basic "Restricted Area";
        auth_basic_user_file /.htpasswd;
    }
    

    # Verstecke versteckte Dateien (.htaccess, .git, etc.)
    location ~ /\. {
        deny all;
        return 404;
    }
    
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/codeways.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/codeways.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.fredima.de) {
        return 301 https://$host$request_uri;
    }
    
    if ($host = fredima.de) {
        return 301 https://$host$request_uri;
    }
    
    server_name fredima.de www.fredima.de;
    listen 80;
    return 404;
}
